# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5ZZ4BJlNzqhsNlBaJsVQP4vcnXJvptH
"""

!apt-get update -qq

!pip install -q pyspark pandas matplotlib

import pandas as pd
import random

from datetime import datetime, timedelta

random.seed(10)

nombres = ["Carlos", "Manuel", "Saul", "Lucía", "María", "Pedro", "Ana", "Jorge", "Sofía", "Luis"]
apellidos = ["Ramirez", "Fernandes", "Sosa", "García", "Torres", "Lopez", "Martinez", "Rojas", "Castillo", "Vega"]

# Generar 200 DNIs únicos
dnis_unicos = random.sample(range(10000000, 99999999), 200)

data = []
for i in range(1, 201):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    dni = str(dnis_unicos[i-1])  # siempre único
    telefono = "9" + str(random.randint(10000000, 99999999))
    direccion = "Calle " + str(random.randint(1, 200)) + " #" + str(random.randint(100, 999))

    data.append([i, nombre, apellido, dni, telefono, direccion])

df = pd.DataFrame(data, columns=["IdCliente","Nombre","Apellido","DNI","Telefono","Direccion"])

print(df.head())

df.to_csv("ClienteServicioTecnico.csv",index=False)

df_pandas = pd.read_csv("ClienteServicioTecnico.csv")

df_pandas.head()

roles = ["Administrador", "Tecnico", "Cliente"]

data = []
for i, rol in enumerate(roles, start=1):
    data.append([i, rol])

df = pd.DataFrame(data, columns=["IdRol","NombreRol"])
print(df.head())

df.to_csv("RolServicioTecnico.csv", index=False)

df1_pandas = pd.read_csv("RolServicioTecnico.csv")

df1_pandas.head()

random.seed(10)

nombres_usuario = ["admin01", "tecnico01", "cliente01", "tecnico02", "cliente02"]
roles = [1, 2, 3, 2, 3]

data = []
for i in range(len(nombres_usuario)):
    usuario = nombres_usuario[i]
    clave = "pass" + str(random.randint(1000,9999))
    idrol = roles[i]
    estado = 1  # activo por defecto


    data.append([usuario, clave, idrol, estado])


df = pd.DataFrame(data, columns=["Usuario","Clave","IdRol","Estado"])

df.to_csv("UsuarioServicioTecnico.csv", index=False)

df2_pandas = pd.read_csv("UsuarioServicioTecnico.csv")

df2_pandas.head()

random.seed(10)

nombres = ["Juan", "Pedro", "Lucía", "María", "Carlos", "Ana", "José", "Sofía"]
apellidos = ["Ramirez", "Fernandes", "Sosa", "García", "Torres", "Lopez", "Martinez", "Rojas"]
especialidades = ["Hardware", "Software", "Redes", "Electrónica", "Mantenimiento"]

data = []

for i in range(1, 51):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    especialidad = random.choice(especialidades)
    telefono = "9" + str(random.randint(10000000, 99999999))

    data.append([nombre, apellido, especialidad, telefono])

df = pd.DataFrame(data, columns=["Nombre", "Apellido", "Especialidad", "Telefono"])
print(df.head())

print(df.shape)

df.to_csv("TecnicoServicioTecnico.csv", index=False)

df3_pandas = pd.read_csv("TecnicoServicioTecnico.csv")

df3_pandas.head()

random.seed(20)


tipos = ["Laptop", "PC", "Celular", "Tablet", "Impresora"]
marcas = ["Dell", "HP", "Lenovo", "Samsung", "Apple", "Canon"]

data = []

num_clientes = 200

for i in range(1,101):
    tipo = random.choice(tipos)
    marca = random.choice(marcas)
    modelo = tipo[:3].upper() + str(random.randint(100,999))
    serie = "SN" + str(random.randint(10000,99999))
    id_cliente = random.randint(1,num_clientes)  # FK hacia Cliente

    data.append([
        i,
        tipo,
        marca,
        modelo,
        serie,
        id_cliente
    ])

df = pd.DataFrame(data, columns=["IdEquipo","Tipo","Marca","Modelo","Serie","IdCliente"])
print(df.head())

df.to_csv("EquipoServicioTecnico.csv", index=False)

df4_pandas = pd.read_csv("EquipoServicioTecnico.csv")

df4_pandas.head()

servicios = [
    ("Mantenimiento preventivo", 50.00),
    ("Reparación de hardware", 120.00),
    ("Instalación de software", 80.00),
    ("Diagnóstico general", 40.00),
    ("Reparación de pantalla", 150.00),
    ("Cambio de batería", 100.00),
    ("Configuración de red", 90.00),
    ("Limpieza interna", 60.00)
]

data = []

for i, (nombre, costo) in enumerate(servicios, start=1):
    data.append([i, nombre, costo])

df = pd.DataFrame(data, columns=["IdServicio","NombreServicio","Costo"])

print(df)

df.to_csv("ServicioServicioTecnico.csv", index=False)

df5_pandas = pd.read_csv("ServicioServicioTecnico.csv")

df5_pandas.head()

repuestos = [
    ("Pantalla LCD", 200.00),
    ("Batería de laptop", 120.00),
    ("Memoria RAM 8GB", 80.00),
    ("Disco SSD 256GB", 150.00),
    ("Fuente de poder", 100.00),
    ("Teclado", 60.00),
    ("Mouse", 25.00),
    ("Placa madre", 250.00),
    ("Cargador universal", 40.00),
    ("Cable HDMI", 15.00)
]

data = []
for i, (nombre, costo) in enumerate(repuestos, start=1):
    data.append([i, nombre, costo])
df = pd.DataFrame(data, columns=["IdRepuesto","NombreRepuesto","Costo"])

print(df)

df.to_csv("RepuestosServicioTecnico.csv", index=False)

random.seed(30)

num_clientes = 200
num_tecnicos = 50
num_equipos = 100

estados = ["Pendiente", "En proceso", "Finalizado", "Cancelado"]
observaciones = [
    "Revisión inicial del equipo",
    "Cambio de pieza principal",
    "Actualización de software",
    "Limpieza y mantenimiento",
    "Diagnóstico completo",
    "Cliente solicita revisión adicional",
    "Equipo entregado sin fallas",
    "Pendiente de repuesto"
]

data = []
for i in range(1, 101):
    id_cliente = random.randint(1, num_clientes)
    id_tecnico = random.randint(1, num_tecnicos)
    id_equipo = random.randint(1, num_equipos)
    fecha = datetime(2026, 7, 1) + timedelta(days=random.randint(0, 30))
    estado = random.choice(estados)
    observacion = random.choice(observaciones)

    data.append([
        id_cliente,
        id_tecnico,
        id_equipo,
        fecha.strftime("%Y-%m-%d"),
        estado,
        observacion
    ])

# Crear DataFrame (sin IdOrden porque es IDENTITY)
df = pd.DataFrame(data, columns=["IdCliente","IdTecnico","IdEquipo","FechaIngreso","Estado","Observacion"])
print(df.head())

df.to_csv("OrdenServicioServicioTecnico.csv", index=False)

random.seed(40)
num_ordenes = 100   # número de órdenes cargadas en tu tabla
num_servicios = 8   # catálogo de servicios
num_detalles = 200  # cantidad de filas de detalle que quieres generar

data = []

for i in range(1, num_detalles+1):
    id_orden = random.randint(1, num_ordenes)   # siempre entre 1 y 100
    id_servicio = random.randint(1, num_servicios)
    cantidad = random.randint(1, 3)
    subtotal = cantidad * random.randint(40, 150)

    data.append([i, id_orden, id_servicio, cantidad, subtotal])

df = pd.DataFrame(data, columns=["IdDetalleOrden","IdOrden","IdServicio","Cantidad","Subtotal"])
print(df.head())

df.to_csv("DetalleOrdenServicioTecnico.csv", index=False)

random.seed(50)


num_ordenes = 150
num_repuestos = 10

data = []

for i in range(1,201):
    id_orden = random.randint(1,num_ordenes)
    id_repuesto = random.randint(1,num_repuestos)
    cantidad = random.randint(1,5)  # cantidad de piezas usadas
    subtotal = cantidad * random.randint(15,250)  # costo simulado

    data.append([
        i,
        id_orden,
        id_repuesto,
        cantidad,
        subtotal
    ])

df = pd.DataFrame(data, columns=["IdDetalleRepuesto","IdOrden","IdRepuesto","Cantidad","Subtotal"])

print(df.head())

df.to_csv("DetalleRepuestoServicioTecnico.csv", index=False)

random.seed(40)
num_ordenes = 100
num_repuestos = 10
num_detalles = 200

data = []

for i in range(1, num_detalles+1):
    id_detalle = i
    id_orden = random.randint(1, num_ordenes)   # siempre entre 1 y 100
    id_repuesto = random.randint(1, num_repuestos)  # siempre entre 1 y 10
    cantidad = random.randint(1, 5)
    subtotal = cantidad * random.randint(20, 100)

    data.append([id_detalle, id_orden, id_repuesto, cantidad, subtotal])

df = pd.DataFrame(data, columns=["IdDetalleRepuesto","IdOrden","IdRepuesto","Cantidad","Subtotal"])
print(df.head())

df.to_csv("DetalleRepuestoServicioTecnico.csv", index=False)

import pandas as pd
import random

# Cargar tu archivo original
df = pd.read_csv("ClienteServicioTecnico.csv")

# Detectar DNIs repetidos
conteo = df["DNI"].value_counts()
repetidos = conteo[conteo > 1].index

# Generar nuevos DNIs únicos para reemplazar los repetidos
usados = set(df["DNI"])
for idx in df[df["DNI"].isin(repetidos)].index:
    while True:
        nuevo_dni = str(random.randint(10000000, 99999999))
        if nuevo_dni not in usados:
            df.at[idx, "DNI"] = nuevo_dni
            usados.add(nuevo_dni)
            break

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

print(df.head())

df.to_csv("ClienteServicioTecnico.csv", index=False)

import pandas as pd
import random

# Cargar tu archivo
df = pd.read_csv("ClienteServicioTecnico.csv")

# Guardar los DNIs ya usados
usados = set(df["DNI"])

# Detectar filas con DNIs repetidos
duplicados = df[df.duplicated(subset="DNI", keep=False)]

# Reemplazar los DNIs repetidos con nuevos únicos
for idx in duplicados.index:
    while True:
        nuevo_dni = str(random.randint(10000000, 99999999))
        if nuevo_dni not in usados:
            df.at[idx, "DNI"] = nuevo_dni
            usados.add(nuevo_dni)
            break

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

# Guardar archivo corregido
df.to_csv("ClienteCorregido.csv", index=False)

df = pd.read_csv("ClienteFinal.csv")

# Crear un conjunto con los DNIs ya usados
usados = set()

# Recorrer todas las filas y corregir si hay repetidos
for idx in df.index:
    dni = str(df.at[idx, "DNI"])
    if dni in usados:
        # Generar un nuevo DNI único
        while True:
            nuevo_dni = str(random.randint(10000000, 99999999))
            if nuevo_dni not in usados:
                df.at[idx, "DNI"] = nuevo_dni
                usados.add(nuevo_dni)
                break
    else:
        usados.add(dni)

# Reasignar IdCliente consecutivo
df["IdCliente"] = range(1, len(df) + 1)

# Guardar archivo limpio
df.to_csv("ClienteUnico.csv", index=False)

df = pd.read_csv("ClienteUnico.csv")

# Verificar si hay DNIs repetidos
repetidos = df[df.duplicated(subset="DNI", keep=False)]

if repetidos.empty:
    print("✅ No hay DNIs repetidos. El archivo está limpio.")
else:
    print("⚠️ Se encontraron DNIs repetidos:")
    print(repetidos[["IdCliente","Nombre","Apellido","DNI"]])